rvm: 1.9.3
language: objective-c
before_script:
   - gem install xcpretty --no-ri --no-rdoc
script:
  - xcodebuild test -workspace FCModel.xcworkspace -scheme FCModel -verbose -configuration Debug -sdk iphonesimulator7.0 -destination 'platform=iOS Simulator,name=iPhone Retina (4-inch),OS=latest'
notifications:
  email: false